<html ng-app="app">
  <head>
    <title>Pienancial</title>

    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <?php echo $app['lstr.asset']->cssTag('app/pienancial/application.css'); ?>
  </head>
  <body>

  <nav class="navbar navbar-default" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Pienancial</a>
      </div>
      <div id="navbar" class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="#">Transactions</a></li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">username <span class="caret"></span></a>
            <ul class="dropdown-menu" role="menu">
              <li><a href="#">Password</a></li>
              <li><a href="#">Settings</a></li>
              <li><a href="#">Sign Out</a></li>
            </ul>
          </li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </nav>

  <div class="container">

    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th>Date</th>
          <th>Merchant</th>
          <th>Amount</th>
          <th>Category</th>
          <th>Description</th>
          <th>Account</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>11/11/2014</td>
          <td>Amazing Restaurant</td>
          <td class="text-right">-19.32</td>
          <td>Dining Out</td>
          <td>Dinner with old friends</td>
          <td>Debit Card 2</td>
        </tr>
        <tr>
          <td>11/11/2014</td>
          <td>Z Groceries</td>
          <td class="text-right">-35.58</td>
          <td>Groceries</td>
          <td>Bread and lunch meat</td>
          <td>Credit Card 1</td>
        </tr>
        <tr>
          <td>11/11/2014</td>
          <td>Z Groceries</td>
          <td class="text-right">-5.00</td>
          <td>Entertainment</td>
          <td>Rootbeer</td>
          <td>Credit Card 1</td>
        </tr>
      </tbody>
    </table>

    Transaction amount: <input type="text" value="45.48" />
    <table class="table table-striped table-bordered table-hover">
      <thead>
        <tr>
          <th>Date</th>
          <th>Merchant</th>
          <th>Amount</th>
          <th>Category</th>
          <th>Description</th>
          <th>Account</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>11/11/2014</td>
          <td>Z Groceries</td>
          <td class="text-right"><input type="text" value="-35.00" /></td>
          <td>Groceries</td>
          <td>Bread and lunch meat</td>
          <td>Credit Card 1</td>
        </tr>
        <tr>
          <td>11/11/2014</td>
          <td>Z Groceries</td>
          <td class="text-right"><input type="text" value="-5.00" /></td>
          <td>Entertainment</td>
          <td>Rootbeer</td>
          <td>Credit Card 1</td>
        </tr>
        <tr>
          <td>11/11/2014</td>
          <td>Z Groceries</td>
          <td class="text-right"><input type="text" value="-10.00" /></td>
          <td>??</td>
          <td>??</td>
          <td>??</td>
        </tr>
        <tr>
          <td></td>
          <td></td>
          <td class="text-right">-0.48</td>
          <td></td>
          <td></td>
          <td></td>
        </tr>
      </tbody>
      </tfoot>
    </table>

  </div><!-- /.container -->


  <?php echo $app['lstr.asset']->jsTag('app/pienancial/application.js'); ?>

  </body>
</html>
